<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>80df710c-cac8-4565-ad18-62c1c118be1c</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <GenerateDocumentationFile>False</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Extensions\ConfigureSwaggerOptions.cs" />
    <Compile Remove="Extensions\SwaggerDefaultValues.cs" />
    <Compile Remove="Extensions\SwaggerExtensions.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Http" Version="8.1.0" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.2" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.0.30" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.OpenTelemetry" Version="4.1.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Aspire.ServiceDefaults\Aspire.ServiceDefaults.csproj" />
    <ProjectReference Include="..\netcoreTemplate.Infrastructure\Infrastructure.csproj" />
  </ItemGroup>
</Project>