<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Interfaces\**" />
    <Compile Remove="Items\Commands\**" />
    <EmbeddedResource Remove="Interfaces\**" />
    <EmbeddedResource Remove="Items\Commands\**" />
    <None Remove="Interfaces\**" />
    <None Remove="Items\Commands\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentResults" Version="3.16.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
    <PackageReference Include="MediatR" Version="12.4.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\netcoreTemplate.Domain\Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Users\Service\" />
  </ItemGroup>
</Project>